# This workflow has been disabled by commenting out the triggers

# schedule:
#   - cron: '0 0 * * *'

# workflow_dispatch:

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - name: Compliance Check
        run: echo 'No compliance checks running since the workflow is disabled.'
